### ISSUE TITLE
Coverage failing

### ISSUE THREAD

**Issue by blond** [enb-make/enb#277]
```
$ npm run coverage
```

```
Coverage saved: /var/folders/77/pjhkfpl903jbxypjy3cbjhq8wyt629/T/coverage557bcff1-1bdb-4f23-a553-abdb469ab9b2.json
  1) lib fs async-fs should return vowFs as it's result:
     TypeError: Cannot read property '1' of undefined
      at Object.countBranch (/Users/blond/projects/enb/lib/fs/require-or-eval.js:400:54)
      at Object.<anonymous> (/Users/blond/projects/enb/lib/fs/async-fs.js:178:22)
      at Module._compile (module.js:460:26)
      at Object.require.extensions..js (/Users/blond/projects/enb/node_modules/unit-coverage/lib/require-replacement.js:45:23)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Context.<anonymous> (/Users/blond/projects/enb/test/lib/fs/async-fs.js:28:31)
      at callFn (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:251:21)
      at Test.Runnable.run (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:244:7)
      at Runner.runTest (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:374:10)
      at /Users/blond/projects/enb/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:299:14)
      at /Users/blond/projects/enb/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:248:23)
      at /Users/blond/projects/enb/node_modules/mocha/lib/runner.js:271:7
      at done (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:207:5)
      at callFn (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:262:7)
      at Hook.Runnable.run (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:244:7)
      at next (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:259:10)
      at Immediate._onImmediate (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:367:17)

  2) lib fs async-fs should not set file limit if it was not defined in process.env:
     TypeError: Cannot read property '1' of undefined
      at Object.countBranch (/Users/blond/projects/enb/lib/fs/require-or-eval.js:400:54)
      at Object.<anonymous> (/Users/blond/projects/enb/lib/fs/async-fs.js:178:22)
      at Module._compile (module.js:460:26)
      at Object.require.extensions..js (/Users/blond/projects/enb/node_modules/unit-coverage/lib/require-replacement.js:45:23)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Context.<anonymous> (/Users/blond/projects/enb/test/lib/fs/async-fs.js:33:17)
      at callFn (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:251:21)
      at Test.Runnable.run (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:244:7)
      at Runner.runTest (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:374:10)
      at /Users/blond/projects/enb/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:299:14)
      at /Users/blond/projects/enb/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:248:23)
      at /Users/blond/projects/enb/node_modules/mocha/lib/runner.js:271:7
      at done (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:207:5)
      at callFn (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:262:7)
      at Hook.Runnable.run (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:244:7)
      at next (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:259:10)
      at Immediate._onImmediate (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:367:17)

  3) lib fs async-fs should set file limit to vow-fs if it was defined in process.env:
     TypeError: Cannot read property '0' of undefined
      at Object.countBranch (/Users/blond/projects/enb/lib/fs/require-or-eval.js:400:54)
      at Object.<anonymous> (/Users/blond/projects/enb/lib/fs/async-fs.js:174:22)
      at Module._compile (module.js:460:26)
      at Object.require.extensions..js (/Users/blond/projects/enb/node_modules/unit-coverage/lib/require-replacement.js:45:23)
      at Module.load (module.js:355:32)
      at Function.Module._load (module.js:310:12)
      at Module.require (module.js:365:17)
      at require (module.js:384:17)
      at Context.<anonymous> (/Users/blond/projects/enb/test/lib/fs/async-fs.js:38:17)
      at callFn (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:251:21)
      at Test.Runnable.run (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:244:7)
      at Runner.runTest (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:374:10)
      at /Users/blond/projects/enb/node_modules/mocha/lib/runner.js:452:12
      at next (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:299:14)
      at /Users/blond/projects/enb/node_modules/mocha/lib/runner.js:309:7
      at next (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:248:23)
      at /Users/blond/projects/enb/node_modules/mocha/lib/runner.js:271:7
      at done (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:207:5)
      at callFn (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:262:7)
      at Hook.Runnable.run (/Users/blond/projects/enb/node_modules/mocha/lib/runnable.js:244:7)
      at next (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:259:10)
      at Immediate._onImmediate (/Users/blond/projects/enb/node_modules/mocha/lib/runner.js:276:5)
      at processImmediate [as _immediateCallback] (timers.js:367:17)



/Users/blond/projects/enb/node_modules/unit-coverage/node_modules/vow/lib/vow.js:104
            throw e;
                  ^
Error: Command failed: node_modules/.bin/mocha --compilers js:/Users/blond/projects/enb/node_modules/unit-coverage/lib/require-replacement.js -u bdd -R spec --recursive techs lib test/lib
Coverage saved: /var/folders/77/pjhkfpl903jbxypjy3cbjhq8wyt629/T/coverage557bcff1-1bdb-4f23-a553-abdb469ab9b2.json

    at ChildProcess.<anonymous> (/Users/blond/projects/enb/node_modules/unit-coverage/lib/utils/subprocess.js:24:26)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

**Comment by blond** [comment]
Coverage failing because call `dropRequireCache`: https://github.com/enb-make/enb/blob/master/test/lib/fs/async-fs.js#L21
